---
title: "Untitled"
author: "brouwern@gmail.com"
date: "May 29, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Whitman et al. 2004. Nature  Featured in Whitlock and Schulter's chapter on regression (Chapter 17).


Whitlock, M.C. and D. Schulter.  The Analysis of Biological Data, 2nd ed.  Robertts and Company, Greenwood Village, CA.

Whitman, K., A.M. Starfield, HS.. Quadling and C. Packer.  2004. Sustainable trophy hunting of African lions.  Nature.
doi:10.1038/nature02395

## Sustainable trophy hunting of African lions.

In most species, sport hunting of male trophy animals can only reduce overall population size when the rate of removal of males is so high that females can no longer be impregnated. However, where males provide extensive paternal care, the removal of even a few individuals could harm the population as a whole. In species such as lions, excessive trophy hunting could theoretically cause male replacements (and associated infanticide) to become sufficiently common to prevent cubs reaching adulthood. Here we simulate the population consequences of lion trophy hunting using a spatially explicit, individual-based, stochastic model parameterized with 40 years of demographic data from northern Tanzania. Although our simulations confirm that infanticide increases the risk of population extinction, trophy hunting could be sustained simply by hunting males above a minimum age threshold, and this strategy maximizes both the quantity and the quality of the long-term kill. We present a simple non-invasive technique for estimating lion age in populations lacking long-term records, and suggest that quotas would be unnecessary in any male-only trophy species where age determination could be reliably implemented.
